updated_client_7/farmers/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views
app_name = 'farmers'
urlpatterns=[
#url(r'^ins',views.insert,name='insert'),
#url(r'^farm',views.farm,name='farm'),
#url(r'^house',views.house,name='house'),
url(r'^form',views.form,name='form'),  
url(r'^sms',views.register,name='sms'),         
url(r'^thanks',views.thanking,name='thanking'),
url(r'^pro',views.prompt,name='prompt'),
#url(r'^img',views.imagere,name='imagere'),
url(r'^familysize',views.housegrp,name='housegrp'),
url(r'^piechart',views.piechart,name='piechart'),
url(r'^welldepth',views.welldepth,name='welldepth'),
url(r'^piemap',views.piemap,name='piemap'),
url(r'^nav',views.first,name='first'),              #this is the main page function
url(r'^wateryield',views.wateryield,name='wateryield'),
url(r'^annualincome',views.annualincome,name='annualincome'),
url(r'^sendtoall',views.sendtoall,name='sendtoall'), 
url(r'^graph',views.graph,name='graph'),
url(r'^checking',views.checking,name='checking'),
url(r'^allhouses',views.AllHouses,name='allhouses'),
url(r'^admin',views.adminform,name='adminform'),
url(r'^aftrlogin',views.aftrlogin,name='aftrlogin'),
url(r'^index',views.button,name='button'),


#url(r'^retri',views.retrieve,name='retrieve'),
]

updated_client_7/village/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^farmers/', include('farmers.urls')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

updated_client_7/farmers/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
#from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.from __future__ import unicode_literals
# Create your models here
class households(models.Model):
	id1=models.IntegerField()
	house_id=models.IntegerField()
	Name=models.CharField(max_length=40)
	lat=models.FloatField()
	lon=models.FloatField()
class UserDetails(models.Model):
	username=models.CharField(max_length=40,null=True)
	mobilenumber=models.IntegerField()
class updatedUserDetails(models.Model):
	username=models.CharField(max_length=40,null=True)
	mobilenumber=models.CharField(max_length=10,null=True)
	#yearly_income=models.FloatField()
	#Area=models.FloatField()
	#isfarm=models.BooleanField()
	

updated_client_7/farmers/forms.py
from django import forms
from django.template.defaultfilters import mark_safe
#from phonenumber_field.formfields import PhoneNumberField

class NameForm(forms.Form):
    house_id= forms.IntegerField(label = mark_safe('<strong>HouseId</strong>'))
class RegForm(forms.Form):
	username=forms.CharField(label=mark_safe('<strong>Username  </strong>'),max_length=20)
	mobile_number=forms.CharField(label=mark_safe('<strong>MobileNumber</strong>'),max_length=10)
class AdminForm(forms.Form):
	admin_username=forms.CharField(label = mark_safe('<strong>Username</strong>'),max_length=20)
	admin_password=forms.CharField(label = mark_safe('<strong>Password</strong>'),max_length=11,widget=forms.PasswordInput)

updated_client_7/farmers/views.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

from django.shortcuts import render
from models import households,updatedUserDetails
from django.http import HttpResponse
from django.template import loader
import urllib
import simplejson
import os
from . forms import NameForm,RegForm,AdminForm
import urllib2
import cookielib
from getpass import getpass
import sys
import os
from stat import *
import numpy as np
from sklearn import datasets, linear_model
import urllib2
import simplejson
import datetime
# Create your views here.


def form(request):
    form = NameForm()
    return render(request, 'farmers/form1.html', {'form': form,'adminform':AdminForm()})
def register(request):
	form=RegForm()
	return render(request,'farmers/form2.html',{'form':form})
def prompt(request):

	if request.method == 'POST':
		form = RegForm(request.POST)
    	if form.is_valid():
        	k=request.POST.get('username')
        	m=request.POST.get('mobile_number')
        	all_details=updatedUserDetails.objects.all()
        	mn=[]
        	for item in all_details:
        		mn.append(item.mobilenumber)
        	if m not in mn:
        		l=updatedUserDetails.objects.create(username=k,mobilenumber=m)
        		l.save()
        		p="You have Successfully registered...!!!"
    		else:
    			p="Mobile number is already registered...!!"
    
	return render(request,'farmers/prompt.html',{'status':p})
def checking(request):
	import numpy as np
	from sklearn import datasets, linear_model
	import urllib2
	import simplejson
	a=[]
	b=[]
	X=[]
	Y=[]
	response = urllib2.urlopen("https://openweathermap.org/data/2.5/forecast/daily?id=1277216&appid=b1b15e88fa797225412429c1c50c122a1")
	data = simplejson.load(response)
	print len(data['list'])
	for i in range(0,14):
	        a=[]
	        Y.append(data['list'][i]['temp']['max'])
	        a.append(data['list'][i]['humidity'])
	        a.append(data['list'][i]['pressure'])
	        a.append(data['list'][i]['speed'])
	        X.append(a)


	regr = linear_model.LinearRegression()


	regr.fit(X, Y)
	a1=X[len(X)-1]
	b1=X[len(X)-2]
	x=[]
	c1=[]
	for i in range(0,len(a1)):
		x.append((a1[i]+b1[i])/2)
	c1.append(x)
	X.append(x)
	y_pred = regr.predict(c1)
	allpredY=regr.predict(X)
	allpredY=allpredY.tolist()
	request.session['temperature']=y_pred[0]
	request.session['actualy']=[]
	request.session['actualy']=Y
	count=len(Y)-1
	l=[]
	year=[]
	month=[]
	day=[]
	for i in range(0,len(Y)+1):
		l.append(datetime.datetime.now()-datetime.timedelta(days=count))
		k=(datetime.datetime.now()-datetime.timedelta(days=count))
		year.append(k.year)
		month.append(k.month-1)
		day.append(k.day)
		count=count-1
		print str(k.month-1) +"*"


	context={'actualy':Y,'predictedy':allpredY,'dates':l,'year':year,'month':month,'day':day}

	#context1={'name':'vasavi'}
	#return HttpResponse(y_pred[0])
	return render(request,'farmers/graphs.html',context)

	#print diabetes_X_train
	#print diabetes_y_train	


def graph(request):
	
	#k=datetime.now()

	l=[]
	actual_y1=request.session['actualy']
	count=len(actual_y1)
	for i in range(0,len(actual_y1)+1):
		l.append(datetime.datetime.now()-datetime.timedelta(days=count))
		count=count-1
	predicted_y1=request.session['predictedy']
	context={'actu_y':actual_y1,'pred_y':predicted_y1,'dates':l}
	return render(request,'farmers/graphs.html',context)



def sendtoall(request):
	message = request.session['temperature']
	k=updatedUserDetails.objects.all()
	l=[]
	for s in k:
		l.append(s.mobilenumber)
	#number = raw_input("Enter number: ")
	#list_num=number.split(' ')
	username = "8500917955"
	passwd = "hiranits7"

	    #message = "+".join(message.split(' '))

	 #logging into the sms site
	url ='http://site24.way2sms.com/Login1.action?'
	data = 'username='+username+'&password='+passwd+'&Submit=Sign+in'

	 #For cookies

	cj= cookielib.CookieJar()
	opener = urllib2.build_opener(urllib2.HTTPCookieProcessor(cj))

	 #Adding header details
	opener.addheaders=[('User-Agent','Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120')]
	try:
		usock =opener.open(url, data)
	except IOError:
		print "error"
	       
	jession_id =str(cj).split('~')[1].split(' ')[0]
	print jession_id
	send_sms_url = 'http://site24.way2sms.com/smstoss.action?'
	for i in range(0,len(l)):
		send_sms_data = 'ssaction=ss&Token='+jession_id+'&mobile='+l[i]+'&message='+'Temperature:'+str(message)+'degree celsius'+'&msgLen=136'
		opener.addheaders=[('Referer', 'http://site25.way2sms.com/sendSMS?Token='+jession_id)]
		try:
			sms_sent_page = opener.open(send_sms_url,send_sms_data)
		except IOError:
			print "error"
		print "success" 
	r='temp:'+str(message)+""+'\n'+'Successfully sent to all'	
	return HttpResponse(r)
	

def thanking(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = NameForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            
            k=request.POST.get('house_id')   #storing house_id in session variable
            k=int(k)
            request.session['hid']=k

	link="http://10.0.3.23:8765/House/?format=json"
	fpoints_link="http://10.0.3.23:8765/farmpoints/?format=json"
	farm_link="http://10.0.3.23:8765/FarmTable/?format=json"
                                                       #loading json data coming from the web server
	f = urllib.urlopen(link)
	myfile = simplejson.load(f)  
	listi=[]
	count=0                                            # converting it into required form putting data in list in lists 
	
	for i in range(0,len(myfile[0])):
		list_temp=[]
		listi.append(list_temp)
	for i in range(0,len(myfile)):
		listi[count].append(myfile[i]['house_id'])
		listi[count+1].append(myfile[i]['lat'])
		listi[count+2].append(myfile[i]['lon'])
		listi[count+3].append(myfile[i]['area'])
		listi[count+4].append(myfile[i]['isfarm'])
		listi[count+5].append(myfile[i]['AnnualIncome'])
	l=[]
	for i in range(0,len(listi[0])):                   #extracting house data related to the entered house_id
		if listi[0][i]==k:
			l.append(listi[1][i])
			l.append(listi[2][i])
			l.append(listi[3][i])
			l.append(listi[5][i])
	#images
	image_link="http://10.0.3.23:8765/imagetable/?format=json"

	f = urllib.urlopen(image_link)                      #loading json data coming from the web server
	myfile = simplejson.load(f)  
	listi=[]
	count=0
	for i in range(0,len(myfile[0])):
		list_temp=[]
		listi.append(list_temp)
	for i in range(0,len(myfile)):
		listi[count].append(myfile[i]['house_idi'])              # converting it into required form putting data in list in lists 
	
		listi[count+1].append(myfile[i]['image'])
	imgtable=""
	for i in range(0,len((listi[0]))):
		if listi[0][i]==k:
			imgtable=imgtable+'http://10.0.3.23:8765'+listi[1][i]+','
	#---img close----		
	imgtable=imgtable.rstrip(',')
	str_imgt=imgtable.split(',')
	#videos
	image_link="http://10.0.3.23:8765/videotable/?format=json"

	f = urllib.urlopen(image_link)                         #loading json data coming from the web server   
	myfile = simplejson.load(f)  
	listi=[]
	count=0
	for i in range(0,len(myfile[0])):                      # converting it into required form putting data in list in lists 
	
		list_temp=[]
		listi.append(list_temp)
	for i in range(0,len(myfile)):
		listi[count].append(myfile[i]['house_idv'])
		listi[count+1].append(myfile[i]['video'])
	vidtable=""
	for i in range(0,len((listi[0]))):
		if listi[0][i]==k:
			vidtable=vidtable+'http://10.0.3.23:8765'+listi[1][i]+','	
	vidtable=vidtable.rstrip(',')
	#----videotable-------
	#strim=str_imgt[0]
	listi=[]
	f = urllib.urlopen(farm_link)                              #loading json data coming from the web server
	myfile1= simplejson.load(f) 
	farm_list=[]
	for i in range(0,len(myfile1[0])):
		list_temp=[]                                            #processing
		listi.append(list_temp)
	for i in range(0,len(myfile1)):
		listi[count].append(myfile1[i]['farm_id'])
		listi[count+1].append(myfile1[i]['area'])
		listi[count+2].append(myfile1[i]['house_farm'])
	m=[]
	m1=[]

	for i in range(0,len(listi[0])):
		if listi[2][i]==k:
			m.append(listi[0][i])
			m1.append(listi[1][i])	
	
	listi=[]
	f = urllib.urlopen(fpoints_link)                                   #loading json data coming from the web server
	myfile2= simplejson.load(f) 
	farm_list=[]
	for i in range(0,len(myfile2[0])):
		list_temp=[]
		listi.append(list_temp)                                       #processing
	for i in range(0,len(myfile2)):
		listi[count].append(myfile2[i]['lat'])
		listi[count+1].append(myfile2[i]['lon'])
		listi[count+2].append(myfile2[i]['farm_idp'])
	n=[]
	if(len(m)!=0):

		for i in m:
			for j in range(0,len(listi[0])):
				if listi[2][j]==i:
					n.append(listi[0][j])
					n.append(listi[1][j])
	mem_link="http://10.0.3.23:8765/mem_details/?format=json"                #loading json data coming from the web server
	f = urllib.urlopen(mem_link)
	myfile3 = simplejson.load(f)  
	listi=[]
	for i in range(0,len(myfile3[0])):
		list_temp=[]
		listi.append(list_temp)
	for i in range(0,len(myfile3)):
		listi[count].append(myfile3[i]['house_idm'])
		listi[count+1].append(myfile3[i]['Name'])

	str1=""
	#str2="vas"
	o=[]
	for i in range(0,len(listi[0])):
		if listi[0][i]==k:
			str1=str1+listi[1][i]+", "
			#o.append(listi[1][i])
	#str1='\n'.join(o)
	str2=str1.rstrip()
	str2=str2.rstrip(',')

	farm_link="http://10.0.3.23:8765/farmcroptable/?format=json"                        #loading json data coming from the web server

	f = urllib.urlopen(farm_link)
	myfile = simplejson.load(f)  
	listi=[]
	for i in range(0,len(myfile[0])):
		list_temp=[]
		listi.append(list_temp)
	for i in range(0,len(myfile)):
		listi[count].append(myfile[i]['season_id'])
		listi[count+1].append(myfile[i]['crop'])
		listi[count+2].append(myfile[i]['farm_idc'])
	fa=""
	if(len(m)!=0):
		for i in m:
			for j in range(0,len(listi[0])):
				if(listi[2][j]==i):
					fa=fa+listi[1][j]+",";


	fa.rstrip(',')	

updated_client_7/farmers/templates/farmers/Upd_wellDepths.html
<!DOCTYPE html>
<html>
<div class="topnav" id="myTopnav">
  <a href="http://10.0.3.23:7777/farmers/form">Home</a>
  <a href="http://10.0.3.23:7777/farmers/allhouses">Households</a>
  <a href="http://10.0.3.23:7777/farmers/piechart">Crop Distribution</a>
  <a class="active" href="http://10.0.3.23:7777/farmers/welldepth">Well depth view</a>
  <a href="http://10.0.3.23:7777/farmers/annualincome">Family Income</a>
  <a href="http://10.0.3.23:7777/farmers/sms">Sign Up</a>
  <a href="http://10.0.3.23:7777/farmers/checking">Analytics</a>
</div> 
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Well depth</title>
    <style>

    .button {
    display: block;
    width: 150px;
    height: 35px;
    background: lightgrey;
    padding: 10px;
    text-align: center;
    border-radius: 5px;
    color: black;
    font-weight: bold;
}
    .topnav {
    background-color: #333;
    overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
}

/* Change the color of links on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}

/* Add a color to the active/current link */
.topnav a.active {
    background-color: lightgrey;
    color: black;
}

.updates  {
  
  text-align :center ;
  font-size : 30px;
  
  
}
.updates img {
  

}

    
      #map {
        height: 90%;
      }
     
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
      #description {
        font-family: Roboto;
        font-size: 15px;
        font-weight: 300;
      }

      #infowindow-content .title {
        font-weight: bold;
      }

      #infowindow-content {
        display: none;
      }

      #map #infowindow-content {
        display: inline;
      }

      .pac-card {
        margin: 50px 50px 0 0;
        border-radius: 2px 0 0 2px;
        box-sizing: border-box;
        -moz-box-sizing: border-box;
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.3);
        background-color: red;
        font-family: Roboto;
      }

      #pac-container {
        padding-bottom: 12px;
        margin-right: 12px;
      }

      .pac-controls {
        display: inline-block;
        padding: 5px 11px;
      }

      .pac-controls label {
        font-family: Roboto;
        font-size: 450px;
        font-weight: 300;
      }

      #pac-input {
        background-color:#e7e7e7;
  
        position: absolute;
        padding: 0 30px 0 13px;

      border-style: solid;
        border-color: black;
        width: 100px;
  height: 75px;
  background: url(/media/well_det.png);
      }
  

      #pac-input:focus {
        border-color: #4d90fe;
      }

      #title {
        color: #fff;
        background-color: #4d90fe;
        font-size: 25px;
        font-weight: 500;
        padding: 6px 12px;
      }
      #target {
        width: 500px;
      }
  
    </style>
  </head>
  <body>
  
<br>
<center><a style="text-decoration:none;" class="button" href="http://10.0.3.23:7777/farmers/wateryield">well depth and wateryield </a></center>


 <center><p><h3>Visualisation of well depths</h3></p></center>

    <div id="pac-input" align="right"></div>
    <div id="map"></div>
    
    <script>


     var p={{list1}};
     var p1={{list2}};
     console.log("info")         //taking content from views
     console.log(p)
     var object=new Array()
     for(i=0;i<p[0].length;i++)
     {
      object[i]=new Array(4)
     }
      for(j=0;j<p[0].length;j++)
      {
      for(i=0;i<=3;i++)             //further processing storing lat,lon,depth in multidimensional array
     {
      object[j][i]=p[i][j]
     }
     }
     var object1=new Array()
     for(i=0;i<p1[0].length;i++)
     {
      object1[i]=new Array(2)
     }
      for(j=0;j<p1[0].length;j++)
      {
      for(i=0;i<=1;i++)
     {
      object1[j][i]=p1[i][j]
     }
     }
     console.log('vas');
     console.log(object);
      

      function initAutocomplete() {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 18.381849, lng:77.875811},
          zoom: 16,
          mapTypeId: 'satellite'
        });

       
       /* var lineSymbol = {
          path: google.maps.SymbolPath.CIRCLE,
          scale: 7,
	 
          strokeColor: '#393',
	
	
        };*/
        
        for(i=0;i<p[0].length;i++)
        {
          var r=(object[i][2])/2;
          var r1=(object[i][2]/10);

        //showing height using polyline 
           markers = new google.maps.Marker({
          position: {lat: object[i][0], lng: object[i][1]},
          map: map,
          Icon : {url:'/media/cylinder.png', scaledSize: new google.maps.Size(40+r1, 50+r)},

        }); 

          farmwindow= new google.maps.InfoWindow();
        //displaying marker for polyline
          farmString='<h3>'+'Depth:'+object[i][2]+' feet'+'</h3>'+'<h3>';

        google.maps.event.addListener(markers,'mouseover', (function(markers,farmString,farmwindow){ 
        return function() {
           farmwindow.setContent(farmString);
           farmwindow.open(map,markers);
        };
    })(markers,farmString,farmwindow));
          //displaying info window on marker
         google.maps.event.addListener(markers,'mouseout',(function(markers,farmString,farmwindow){ 
          return function() {
           farmwindow.close();
        };
    })(markers,farmString,farmwindow));



        
      }
      var input = document.getElementById('pac-input');
        var searchBox = new google.maps.places.SearchBox(input);
        map.controls[google.maps.ControlPosition.TOP_RIGHT].push(input);
  

        
        map.addListener('bounds_changed', function() {
          searchBox.setBounds(map.getBounds());
        });

	}
     
      
    </script>
   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBQUuaVeif3WTTX_8Y-kvHImqu3Cm_02Wo&libraries=places&callback=initAutocomplete"
         async defer></script>
    <br>
    <center><a href="http://10.0.3.23:7777/farmers/wateryield">well depth and wateryield </a></center>

  </body>
</html>

updated_client_7/farmers/templates/farmers/aftrlogin.html
<html>
<style>
.button {
    display: block;
    width: 150px;
    height: 25px;
    background: lightgrey;
    padding: 10px;
    text-align: center;
    border-radius: 5px;
    color: black;
    font-weight: bold;
}
</style>

<div id="cont1" align="center">
	<a href='http://10.0.3.23:7777/farmers/sendtoall' id='btn' class="button" style="text-decoration:none;">Send To All</a></div>
<script>
var status="{{status}}"

if(status=="ok")
{
document.getElementById("cont1").style.visibility="visible";
	console.log(status);

}
if(status=="not ok")
{
	document.getElementById("cont1").style.visibility="hidden";
	console.log(status);
}
</script>
<body>

</body></html>

updated_client_7/farmers/templates/farmers/annualincome.html
<!DOCTYPE html>
<html>
<div class="topnav" id="myTopnav">
  <a href="http://10.0.3.23:7777/farmers/form">Home</a>
  <a href="http://10.0.3.23:7777/farmers/allhouses">Households</a>
  <a href="http://10.0.3.23:7777/farmers/piechart">Crop Distribution</a>
  <a href="http://10.0.3.23:7777/farmers/welldepth">Well depth view</a>
  <a class="active" href="http://10.0.3.23:7777/farmers/annualincome">Family Income</a>
  <a href="http://10.0.3.23:7777/farmers/sms">Sign Up</a>
  <a href="http://10.0.3.23:7777/farmers/checking">Analytics</a>
</div> 
  <head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Circles</title>
    <style>
    .topnav {
    background-color: #333;
    overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
}

/* Change the color of links on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}

/* Add a color to the active/current link */
.topnav a.active {
    background-color: lightgrey;
    color: black;
}

.updates  {
  
  text-align :center ;
  font-size : 30px;
  
  
}
.updates img {
  

}

      
      #map {
        height: 100%;
      }
      
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <center><p><h3>Visualisation of houses based on Annual Income</h3></p></center>
    <div id="map"></div>
    <script>
      
    
      var h={{list1}}   //retrieving content from the views
      
      function initMap() {
        // Create the map.
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 18,
          center: {lat: 18.381849, lng: 77.875811},
          mapTypeId: 'satellite'
        });

        // Construct the circle for each value in cityCircle.
        // Note: We scale the area of the circle based on the familyincome 
        for (i=0;i<h[0].length;i++) {
          
          var cityCircle = new google.maps.Circle({
            strokeColor: '#FF0000',
            strokeOpacity: 0.8,
            strokeWeight: 2,
            fillColor: '#FF0000',
            fillOpacity: 0.35,
            map: map,
            title:'House-id:'+h[0][i].toString()+" "+'Family Income:'+h[3][i].toString(),
            center: {lat: h[1][i], lng: h[2][i]},
            radius: (h[3][i]) /10000
          });

          //displaying family details when place mouse on the circle 
           google.maps.event.addListener(cityCircle,'mouseover',function(){
             this.getMap().getDiv().setAttribute('title',this.get('title'));});

        google.maps.event.addListener(cityCircle,'mouseout',function(){
             this.getMap().getDiv().removeAttribute('title');});
        }
      }
    </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBQUuaVeif3WTTX_8Y-kvHImqu3Cm_02Wo&callback=initMap">
    </script>
  </body>
</html>

updated_client_7/farmers/templates/farmers/form3.html
{{form.username}}

updated_client_7/farmers/templates/farmers/login.html
<div class="topnav" id="myTopnav">
  <a href="http://127.0.0.1:8000/farmers/form">Home</a>
  <a href="http://127.0.0.1:8000/farmers/familysize">Households</a>
  <a href="http://127.0.0.1:8000/farmers/piechart">Crop Distribution</a>
  <a href="http://127.0.0.1:8000/farmers/welldepth">Well depth view</a>
  <a href="http://127.0.0.1:8000/farmers/annualincome">Family Income</a>
  <a class="active" href="http://127.0.0.1:8000/farmers/sms">Sign Up</a>
  <a href="http://127.0.0.1:8000/farmers/checking">Analytics</a>
</div> 

<div class= "updates" id="update">


</div>
<style>

.topnav {
    background-color: #333;
    overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
}

/* Change the color of links on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}

/* Add a color to the active/current link */
.topnav a.active {
    background-color: lightgrey;
    color: black;
}

.updates  {
	
	text-align :center ;
	font-size : 30px;
	
	
}
.updates img {
	

}

</style>





<form action="{% url 'farmers:aftrlogin' %}" method="post">
    {% csrf_token %}
    <center>
    {{ form.as_p }}


    <input type="submit" value="Submit" /></center></body>
    </html>

updated_client_7/farmers/templates/farmers/nav.html
<!DOCTYPE html> 
<html>
<div class="topnav" id="myTopnav">
  <a href="http://127.0.0.1:8000/farmers/form">Home</a>
  <a href="http://127.0.0.1:8000/farmers/familysize">Households</a>
  <a href="http://127.0.0.1:8000/farmers/piechart">Crop Distribution</a>
  <a href="http://127.0.0.1:8000/farmers/welldepth">Well depth view</a>
  <a href="http://127.0.0.1:8000/farmers/annualincome">Family Income</a>
</div> 

<div class= "updates" id="update">
<marquee directon ="up"><img src="http://www.animatedgif.net/new/nunew_e0.gif"/>
<p>Andhra pradesh</p>
</marquee>
</div>
<style>

.topnav {
    background-color: #333;
    overflow: hidden;
}

/* Style the links inside the navigation bar */
.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
}

/* Change the color of links on hover */
.topnav a:hover {
    background-color: #ddd;
    color: black;
}

/* Add a color to the active/current link */
.topnav a.active {
    background-color: #4CAF50;
    color: white;
}

.updates  {
	
	text-align :center ;
	font-size : 30px;
	
	
}
.updates img {
	

}

</style>
<script>console.log({{list1}})</script>
<body background ="/media/crops.jpg"></body>
</html>